package com.business.inventra.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.business.inventra.util.KeyGenerator;

@Data
@Entity
@Table(name = "customer_branch_mapping", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"customerID", "branchID"})
})
@EqualsAndHashCode(callSuper = true)
public class CustomerBranchMapping extends BaseModel {
    private static final String CUSTOMER_BRANCH_PREFIX = KeyGenerator.CUSTOMER_BRANCH_PREFIX;

    @Column(name = "customerID", nullable = false)
    private String customerID;

    @Column(name = "branchID", nullable = false)
    private String branchID;

    @Column(name = "orgID", nullable = false)
    private String orgID;

    @Column(name = "userId", nullable = true)
    private String userId;  // Stores the user ID if the customer is also a user

    public CustomerBranchMapping() {
        this.prefix = CUSTOMER_BRANCH_PREFIX;
    }

	public String getCustomerID() {
		return customerID;
	}

	public void setCustomerID(String customerID) {
		this.customerID = customerID;
	}

	public String getBranchID() {
		return branchID;
	}

	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	public String getOrgID() {
		return orgID;
	}

	public void setOrgID(String orgID) {
		this.orgID = orgID;
	}

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    // Getters and setters generated by Lombok (@Data)
    
    
}
